window.BIRTHDAY = {
  password: "roham",
  scenes: [
    {
      id: "first-glance",
      tone: "soft",
      kicker: "01 · The beginning",
      title: "The first time I saw you",
      text: "Yeh woh picture hai jab maine apko pehli dafa dekha tha, phir rishty ki baat chali thi. Kash tab pata hota ke apki ek ankh chhoti hai, to tab hi kuch soch leta Jaan. Lekin soch ke bhi kya karta, dil to tab bhi apka hi ho gaya tha.",
      image: "images/opt/first-time.webp",
    },
    {
      id: "childhood",
      tone: "soft",
      kicker: "02 · Before us",
      title: "The little storm before the queen",
      text: "Yeh piddi si tasveer hai Mera Bacha. Kash pehle dekh li hoti, tab hi pata chal jata ke ismein yeh larki mastikhor hai. Isi chhoti si smile mein wohi masti thi jo aaj bhi mujhe paagal karti hai.",
      image: "images/opt/childhood.webp",
    },
    {
      id: "burkha",
      tone: "playful",
      kicker: "03 · My mystery",
      title: "Burkha ninja",
      text: "Yeh burkha maine shadi se pehle har baar dekha hai Jaan. Ab dekho, rich ho gayi hain, 3 3 ho gaye. Wah kya baat hai. Pehle ek, ab collection. Mera burkha ninja upgrade ho gaya.",
      image: "images/opt/burkha-ninja.webp",
    },
    {
      id: "desire",
      tone: "intimate",
      kicker: "04 · Only ours",
      title: "When my body learned your name",
      text: "Is picture ke baad mujhe woh pehli raat yaad aati hai jab ghar koi nahi tha. Full night call pe masti ki thi humne Mera Bacha. Us din apka geelapan dekha tha, aur us raat se yeh moment sirf humara hai.",
      image: "images/opt/first-desire.webp",
    },
    {
      id: "love-bite",
      tone: "intimate",
      kicker: "05 · Marked",
      title: "Love bite",
      text: "Shadi ke shuru ke din apki yeh neck kabhi saaf hoti hi nahi thi Jaan. Soft skin pe yeh nishaan dekh ke ab bhi smile aa jati hai. Us time kya kya try kiya, kitni sex positions, kitni masti. Sach mein kitna maze ka time tha, bilkul humara.",
      image: "images/opt/love-bite.webp",
    },
    {
      id: "eyes",
      tone: "romantic",
      kicker: "06 · Soft fire",
      title: "Love living in your eyes",
      text: "Jab ap aise dekhti hain na Jaan to meri saari gussa nikal jati hai. Apki aankhon mein itna pyaar hai ke main bas ruk jata hoon. Sach mein apki nazar mujhe ghar jaisa feel karati hai.",
      image: "images/opt/love-in-eyes.webp",
    },
    {
      id: "scent",
      tone: "intimate",
      kicker: "07 · After the shower",
      title: "That scent I still chase",
      text: "Jab ap apni khushboo smell kar lein aur khud se hi barshash na ho jaye, yeh wali photo yaad aati hai Mera Bacha. Funny hai, joke hai, lekin bilkul ap jaisi masti hai Jaan.",
      image: "images/opt/after-shower.webp",
    },
    {
      id: "perfect",
      tone: "romantic",
      kicker: "08 · Us",
      title: "Perfect couple, imperfect days",
      text: "Hum perfect isliye nahi ke roz soft din hote hain. Perfect isliye hain ke ladne ke baad bhi hum ek doosre ke paas aa jate hain. Ap meri chaos bhi hain aur meri sukoon bhi Jaan.",
      image: "images/opt/perfect-couple.webp",
    },
    {
      id: "clingy",
      tone: "playful",
      kicker: "09 · Attitude",
      title: "Pehle chipakti thi…",
      text: "Pehle ap mujhse chipakti thin na jaise glue. Ab thoda attitude wali queen ban gayi hain. Lekin hasi aati hai ke main ab bhi apke peeche hi bhagta hoon Brhy Boobs wali. Ap meri hi hain.",
      image: "images/opt/clingy-days.webp",
    },
    {
      id: "old-days",
      tone: "romantic",
      kicker: "10 · Golden reel",
      title: "Old good days",
      text: "Woh subah ke din yaad aate hain Jaan. Padhte rehte the, chai naan chany, bike rides, saman lene jana. Sab maze ka tha. Main woh din phir jeena chahta hoon sirf apke saath.",
      image: "images/opt/old-days.webp",
    },
    {
      id: "favorite",
      tone: "romantic",
      kicker: "11 · Forever frame",
      title: "My favourite of all time",
      text: "Agar mujhe forever ke liye ek hi photo rakhni ho to woh yeh hi hogi. Maliha Fahad ap meri favourite picture hain, meri craze hain, meri poori gallery hain. Bas ap.",
      image: "images/opt/favorite.webp",
    },
    {
      id: "mula",
      tone: "playful",
      kicker: "12 · Chaos soft",
      title: "Mula Jutt energy",
      text: "Apka drama, apki jokes, apke mood swings, sab mil ke ap ordinary din ko bhi interesting bana deti hain. Main apka fan hoon Mera Bacha. Apki energy hi meri smile hai.",
      image: "images/opt/mula-jutt.webp",
    },
    {
      id: "moment",
      tone: "soft",
      kicker: "13 · Quiet",
      title: "A moment I never posted",
      text: "Har cheez post nahi karni hoti. Kuch moments sirf hum dono ke hote hain, quiet aur warm. Yeh wala bhi wahi hai Jaan. Isliye main isko kisi ko nahi dikhata, sirf apne dil mein rakhta hoon.",
      image: "images/opt/moment.webp",
    },
    {
      id: "funny",
      tone: "playful",
      kicker: "14 · My comedian",
      title: "That weird face I adore",
      text: "Yeh weird face dekh ke bhi mujhe hasi aa jati hai. Isliye main apko Mera Bacha kehta hoon. Silly bhi hain, soft bhi hain, aur meri favourite comedian bhi. Apki har face mujhe pyari lagti hai.",
      image: "images/opt/funny-face.webp",
    },
    {
      id: "dressed",
      tone: "romantic",
      kicker: "15 · Dressed in us",
      title: "My wife, well dressed in love",
      text: "Apke saath khade hone pe lagta hai ke maine life jeet li hai. Itni khoobsurat, itni meri. Meri biwi, meri pride, aur haan meri thodi si hunger bhi. I love you dressed like this Jaan.",
      image: "images/opt/well-dressed.webp",
    },
    {
      id: "mother",
      tone: "family",
      kicker: "16 · Motherhood",
      title: "Roham’s mother",
      text: "Apko Ammi bante dekh ke main sach mein badal gaya. Itni strong, itni soft, itni caring. Ap sirf meri Jaan nahi hain, ap Roham ki duniya bhi hain. Aur main is pe bohot proud hoon.",
      image: "images/opt/roham-mother.webp",
    },
    {
      id: "newborn",
      tone: "family",
      kicker: "17 · Third heartbeat",
      title: "When Roham was brand new",
      text: "Us din chhote se haath mein itna bada pyaar aa gaya tha. Hamari story mein teesri heartbeat aa gayi thi. Aur ap itni glow kar rahi thin Jaan ke lag raha tha sab kuch perfect ho gaya.",
      image: "images/opt/newborn-roham.webp",
    },
    {
      id: "son",
      tone: "family",
      kicker: "18 · Our boy",
      title: "Love of our beautiful son",
      text: "Yeh hamara beta hai, hamara proof. Har ladai ke baad bhi yeh soch ke dil soft ho jata hai ke humne yeh ghar banaya. Apki god, meri dua, humara Roham. Bas yehi family hai meri.",
      image: "images/opt/beautiful-son.webp",
    },
    {
      id: "dupatta",
      tone: "family",
      kicker: "19 · Tenderness",
      title: "Dupatta games & soft smiles",
      text: "Uske saath ap jo chhoti chhoti khushiyan banati hain na, woh mujhe bohot soft feel karati hai. Dupatta games, soft smiles, yehi apki asli beauty hai Jaan. Ghar wali sexy, dil wali sexy.",
      image: "images/opt/dupatta-play.webp",
    },
    {
      id: "cake",
      type: "cake",
      tone: "celebrate",
      kicker: "20 · Birthday night",
      title: "Make a wish, Maliha Fahad",
      text: "Cake pakad Jaan aur candle bujha. Har saal ap ne meri life soft banayi hai, pyari banayi hai, aur thodi hotter bhi. Wish maang le. Main already apka hoon, hamesha se.",
      image: "images/opt/birthday-cake.webp",
    },
    {
      id: "letter",
      type: "letter",
      tone: "letter",
      kicker: "Final letter",
      title: "To my Maliha Fahad",
    },
    {
      id: "the-end",
      type: "ending",
      tone: "intimate",
      kicker: "Only yours",
      title: "I love you",
      text: "Meri naughty wife. Meri lingerie wali Jaan. Meri hunger. Meri forever.",
      image: "images/opt/favorite.webp",
    },
  ],
};
